import "./globals.css";
import { ThemeModeScript } from "flowbite-react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
        
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
